In [5]:
import numpy as np
from scipy import stats

In [6]:
#initialization

In [7]:
X =  np.array([[-3,0],[-2.5,0],[-1,0],[0,1],[2,1],[4,0],[5,1]])
S = np.array([[1,1],[0.2,0],[3,0]])
S = np.sqrt(S)
M =  np.array([[-4,0],[0,0],[8,0]])
P = np.array([[1/3,1/3,1/3]])

In [68]:
X =  np.array([[-3],[-2.5],[-1],[0],[2],[4],[5]])
S = np.array([[1],[0.2],[3]])
S = np.sqrt(S)
M =  np.array([[-4],[0],[8]])
P = np.array([[1/3,1/3,1/3]])

In [282]:
def calc_G(X, M, S):  # returns an (N x K) array
    G = []
    for Xn in X[:]:
        G.append([stats.norm(Mk,Sk).pdf(Xn) for Mk,Sk in zip(M,S)] )
        
    G = P * np.array(G)[:,:,0]
    G = G / np.sum(G , axis=1).reshape(-1,1)
    return G

def calc_Nk(G):   # returns an (1 x K) array
    return np.sum(G , axis=0).reshape(-1,1)
    
def calc_M(X, G, Nk): # returns an (K x D) array
    return G.T.dot(X) / Nk

def calc_S(X, G, Nk, M):
    diff = X - M.T
    print(diff.shape)
    print(G.shape)
    return G.T.dot(diff)


In [283]:
M - X.T

array([[-1. , -1.5, -3. , -4. , -6. , -8. , -9. ],
       [ 3. ,  2.5,  1. ,  0. , -2. , -4. , -5. ],
       [11. , 10.5,  9. ,  8. ,  6. ,  4. ,  3. ]])

In [284]:
g = calc_G(X, M, S)
nk =calc_Nk(g)
m = calc_M(X, g, nk)
s = calc_S(X, g , nk , m)

(7, 3)
(7, 3)


In [285]:
calc_M(X, g, nk)

array([[-2.70123001],
       [-0.40341072],
       [ 3.70428735]])

In [293]:
m = np.array([[1],[1],[2]])

In [294]:
X

array([[-3. ],
       [-2.5],
       [-1. ],
       [ 0. ],
       [ 2. ],
       [ 4. ],
       [ 5. ]])

In [297]:
m - X.T

array([[ 4. ,  3.5,  2. ,  1. , -1. , -3. , -4. ],
       [ 4. ,  3.5,  2. ,  1. , -1. , -3. , -4. ],
       [ 5. ,  4.5,  3. ,  2. ,  0. , -2. , -3. ]])

In [271]:
s.shape

(3, 3)

In [ ]:
while True:
    G = P @ stats.norm(M,S).pdf(X)
    G = G / np.sum(G , axis=0)
    Nk = np.sum(G , axis=1)
    
    break